### ISSUE TITLE
blur and boxBlur produce a black canvas

### ISSUE THREAD

**Issue by kikiminou** [SeeDoubleYou/jquery-tocanvas#1]
I found that when using the filters _blur_ or _boxBlur_ the result is always a black canvas.

I found why : for these functions convolutionFilter is not called with the expected parameters.

I just replaced the last line
`return this.convolutionFilter(filter, options);`
with
`return this.convolutionFilter($.extend({}, options, {filter:filter}));`
and this is it !

Nice job anyway,

Thanks for sharing ;-)

**Comment by SeeDoubleYou** [comment]
Thanks @kikiminou!
